apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: name
        image: Enter containers image
        resources: 
          limits: 
            cpu: "200m"
            memory: "500Mi"
  
      volumes:
        - name:  name of the volume
          mountPath: /tmp/lib/netcore

          