apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
spec:
  capacity:
    storage: 10Gi

  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany 
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:   # 存储类型 nfs  网格文件服务器
    path: /tmp
    server: 172.17.0.2
  
  azureDisk: 
